import type {
  DifficultyLevel,
  DurationBucket,
  InterviewTrack,
  RecentSession,
  TrackFormat,
  TrackRoleFamily,
} from "./types"

export const INTERVIEW_TRACKS: readonly InterviewTrack[] = [
  {
    id: "behavioral",
    iconName: "MessageSquare",
    difficulty: "adaptive",
    taskCount: 6,
    format: "conversation",
    durationMin: 25,
    roleFamilies: ["general", "engineering", "product", "design", "finance", "consulting", "clinical"],
    titleKey: "simulations.tracks.behavioral.title",
    descriptionKey: "simulations.tracks.behavioral.description",
  },
  {
    id: "technical-coding",
    iconName: "Code2",
    difficulty: "hard",
    taskCount: 3,
    format: "codeRun",
    durationMin: 45,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.technicalCoding.title",
    descriptionKey: "simulations.tracks.technicalCoding.description",
  },
  {
    id: "live-coding",
    iconName: "Terminal",
    difficulty: "hard",
    taskCount: 2,
    format: "workspace",
    durationMin: 50,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.liveCoding.title",
    descriptionKey: "simulations.tracks.liveCoding.description",
  },
  {
    id: "ops-terminal",
    iconName: "Server",
    difficulty: "medium",
    taskCount: 4,
    format: "terminal",
    durationMin: 40,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.opsTerminal.title",
    descriptionKey: "simulations.tracks.opsTerminal.description",
  },
  {
    id: "system-design",
    iconName: "Network",
    difficulty: "hard",
    taskCount: 1,
    format: "conversation",
    durationMin: 40,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.systemDesign.title",
    descriptionKey: "simulations.tracks.systemDesign.description",
  },
  {
    id: "product-sense",
    iconName: "Lightbulb",
    difficulty: "medium",
    taskCount: 4,
    format: "conversation",
    durationMin: 30,
    roleFamilies: ["product", "design"],
    titleKey: "simulations.tracks.productSense.title",
    descriptionKey: "simulations.tracks.productSense.description",
  },
  {
    id: "case-study",
    iconName: "Monitor",
    difficulty: "medium",
    taskCount: 2,
    format: "conversation",
    durationMin: 35,
    roleFamilies: ["consulting", "product", "finance"],
    titleKey: "simulations.tracks.caseStudy.title",
    descriptionKey: "simulations.tracks.caseStudy.description",
  },
  {
    id: "finance-quant",
    iconName: "TrendingUp",
    difficulty: "hard",
    taskCount: 8,
    format: "codeRun",
    durationMin: 30,
    roleFamilies: ["finance"],
    titleKey: "simulations.tracks.financeQuant.title",
    descriptionKey: "simulations.tracks.financeQuant.description",
  },
  {
    id: "pm-strategy",
    iconName: "Target",
    difficulty: "medium",
    taskCount: 5,
    format: "conversation",
    durationMin: 35,
    roleFamilies: ["product"],
    titleKey: "simulations.tracks.pmStrategy.title",
    descriptionKey: "simulations.tracks.pmStrategy.description",
  },
  {
    id: "leadership",
    iconName: "Users",
    difficulty: "adaptive",
    taskCount: 6,
    format: "conversation",
    durationMin: 25,
    roleFamilies: ["general", "engineering", "product", "design", "finance", "consulting"],
    titleKey: "simulations.tracks.leadership.title",
    descriptionKey: "simulations.tracks.leadership.description",
  },
  {
    id: "data-analytics",
    iconName: "BarChart2",
    difficulty: "medium",
    taskCount: 4,
    format: "codeRun",
    durationMin: 30,
    roleFamilies: ["engineering", "product", "finance"],
    titleKey: "simulations.tracks.dataAnalytics.title",
    descriptionKey: "simulations.tracks.dataAnalytics.description",
  },
  {
    id: "communication",
    iconName: "Mic2",
    difficulty: "easy",
    taskCount: 4,
    format: "conversation",
    durationMin: 20,
    roleFamilies: ["general", "engineering", "product", "design", "finance", "consulting", "clinical"],
    titleKey: "simulations.tracks.communication.title",
    descriptionKey: "simulations.tracks.communication.description",
  },
] as const

export const TRACK_DIFFICULTIES: readonly DifficultyLevel[] = [
  "adaptive",
  "easy",
  "medium",
  "hard",
] as const

/** Practice environment formats (filter order). */
export const TRACK_FORMATS: readonly TrackFormat[] = [
  "codeRun",
  "workspace",
  "terminal",
  "conversation",
] as const

export const TRACK_ROLE_FAMILIES: readonly TrackRoleFamily[] = [
  "engineering",
  "product",
  "design",
  "finance",
  "consulting",
  "clinical",
  "general",
] as const

export const TRACK_DURATION_BUCKETS: readonly DurationBucket[] = [
  "short",
  "medium",
  "long",
] as const

/** Mock history until sessions API lands — dates relative to “now” for formatRelativeTime. */
function daysAgoIso(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(14, 30, 0, 0)
  return d.toISOString()
}

export const MOCK_RECENT_SESSIONS: readonly RecentSession[] = [
  {
    id: "s1",
    title: "Senior Product Designer",
    track: "Behavioral",
    trackId: "behavioral",
    updatedAt: daysAgoIso(2),
    durationMin: 24,
    score: 82,
    status: "completed",
  },
  {
    id: "s2",
    title: "Staff Engineer",
    track: "System Design",
    trackId: "system-design",
    updatedAt: daysAgoIso(5),
    durationMin: 38,
    score: 74,
    status: "completed",
  },
  {
    id: "s3",
    title: "PM, Growth",
    track: "Product Sense",
    trackId: "product-sense",
    updatedAt: daysAgoIso(7),
    durationMin: 18,
    score: null,
    status: "in_progress",
  },
  {
    id: "s4",
    title: "SRE",
    track: "Ops · Shell lab",
    trackId: "ops-terminal",
    updatedAt: daysAgoIso(12),
    durationMin: 12,
    score: null,
    status: "abandoned",
  },
  {
    id: "s5",
    title: "JavaScript · Sum lines",
    track: "Code run",
    trackId: "technical-coding",
    updatedAt: daysAgoIso(1),
    durationMin: 8,
    score: 91,
    status: "completed",
  },
] as const
