import type { InterviewTrack, RecentSession } from "./types"

/**
 * Live practice surfaces.
 * IDE ids match IdeFormatSlug / exercise catalog slug.
 * Conversation ids route to `/simulations/conversation/:trackId`.
 */
export const INTERVIEW_TRACKS: readonly InterviewTrack[] = [
  {
    id: "behavioral-core",
    iconName: "MessageSquare",
    difficulty: "medium",
    taskCount: 5,
    format: "conversation",
    durationMin: 20,
    roleFamilies: ["general", "product", "engineering", "design", "consulting"],
    titleKey: "simulations.tracks.behavioralCore.title",
    descriptionKey: "simulations.tracks.behavioralCore.description",
  },
  {
    id: "product-sense",
    iconName: "Lightbulb",
    difficulty: "medium",
    taskCount: 5,
    format: "conversation",
    durationMin: 25,
    roleFamilies: ["product", "general"],
    titleKey: "simulations.tracks.productSense.title",
    descriptionKey: "simulations.tracks.productSense.description",
  },
  {
    id: "system-design-talk",
    iconName: "Network",
    difficulty: "hard",
    taskCount: 5,
    format: "conversation",
    durationMin: 30,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.systemDesignTalk.title",
    descriptionKey: "simulations.tracks.systemDesignTalk.description",
  },

  {
    id: "js-sum",
    iconName: "Code2",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 15,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.jsSum.title",
    descriptionKey: "simulations.tracks.jsSum.description",
  },
  {
    id: "ts-sum",
    iconName: "FileText",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 15,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.tsSum.title",
    descriptionKey: "simulations.tracks.tsSum.description",
  },
  {
    id: "py-hello",
    iconName: "Code2",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 15,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.pyHello.title",
    descriptionKey: "simulations.tracks.pyHello.description",
  },
  {
    id: "js-fizzbuzz",
    iconName: "Hash",
    difficulty: "easy",
    taskCount: 2,
    format: "codeRun",
    durationMin: 20,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.jsFizzbuzz.title",
    descriptionKey: "simulations.tracks.jsFizzbuzz.description",
  },
  {
    id: "js-reverse",
    iconName: "Scan",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 10,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.jsReverse.title",
    descriptionKey: "simulations.tracks.jsReverse.description",
  },
  {
    id: "py-factorial",
    iconName: "Activity",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 12,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.pyFactorial.title",
    descriptionKey: "simulations.tracks.pyFactorial.description",
  },
  {
    id: "ts-palindrome",
    iconName: "FileText",
    difficulty: "medium",
    taskCount: 3,
    format: "codeRun",
    durationMin: 15,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.tsPalindrome.title",
    descriptionKey: "simulations.tracks.tsPalindrome.description",
  },
  {
    id: "py-vowels",
    iconName: "Mic2",
    difficulty: "easy",
    taskCount: 3,
    format: "codeRun",
    durationMin: 10,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.pyVowels.title",
    descriptionKey: "simulations.tracks.pyVowels.description",
  },
  {
    id: "cpp-sort",
    iconName: "Code2",
    difficulty: "medium",
    taskCount: 1,
    format: "codeRun",
    durationMin: 30,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.cppSort.title",
    descriptionKey: "simulations.tracks.cppSort.description",
  },
  {
    id: "react",
    iconName: "Monitor",
    difficulty: "medium",
    taskCount: 1,
    format: "workspace",
    durationMin: 25,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.react.title",
    descriptionKey: "simulations.tracks.react.description",
  },
  {
    id: "shell",
    iconName: "Terminal",
    difficulty: "medium",
    taskCount: 1,
    format: "terminal",
    durationMin: 20,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.shell.title",
    descriptionKey: "simulations.tracks.shell.description",
  },
  {
    id: "workspace",
    iconName: "Server",
    difficulty: "medium",
    taskCount: 1,
    format: "workspace",
    durationMin: 30,
    roleFamilies: ["engineering"],
    titleKey: "simulations.tracks.workspace.title",
    descriptionKey: "simulations.tracks.workspace.description",
  },
  {
    id: "spreadsheet",
    iconName: "Table2",
    difficulty: "medium",
    taskCount: 1,
    format: "spreadsheet",
    durationMin: 25,
    roleFamilies: ["finance", "consulting", "engineering", "general"],
    titleKey: "simulations.tracks.spreadsheet.title",
    descriptionKey: "simulations.tracks.spreadsheet.description",
  },
  {
    id: "page",
    iconName: "FileText",
    difficulty: "medium",
    taskCount: 1,
    format: "page",
    durationMin: 30,
    roleFamilies: ["consulting", "product", "finance", "general"],
    titleKey: "simulations.tracks.page.title",
    descriptionKey: "simulations.tracks.page.description",
  },
] as const

/** History is server-backed via voice.listSessions — no hard-coded rows. */
export const MOCK_RECENT_SESSIONS: readonly RecentSession[] = []
