import type { InterviewTrack, RecentSession } from "./types"

export const INTERVIEW_TRACKS: readonly InterviewTrack[] = [
  {
    id: "behavioral",
    iconName: "MessageSquare",
    difficulty: "adaptive",
    metaCount: 6,
    metaKind: "questions",
    durationMin: 25,
    titleKey: "simulations.tracks.behavioral.title",
    descriptionKey: "simulations.tracks.behavioral.description",
  },
  {
    id: "technical-coding",
    iconName: "Code2",
    difficulty: "hard",
    metaCount: 3,
    metaKind: "problems",
    durationMin: 45,
    titleKey: "simulations.tracks.technicalCoding.title",
    descriptionKey: "simulations.tracks.technicalCoding.description",
  },
  {
    id: "system-design",
    iconName: "Network",
    difficulty: "hard",
    metaCount: 1,
    metaKind: "prompt",
    durationMin: 40,
    titleKey: "simulations.tracks.systemDesign.title",
    descriptionKey: "simulations.tracks.systemDesign.description",
  },
  {
    id: "product-sense",
    iconName: "Lightbulb",
    difficulty: "medium",
    metaCount: 4,
    metaKind: "questions",
    durationMin: 30,
    titleKey: "simulations.tracks.productSense.title",
    descriptionKey: "simulations.tracks.productSense.description",
  },
  {
    id: "case-study",
    iconName: "Monitor",
    difficulty: "medium",
    metaCount: 2,
    metaKind: "cases",
    durationMin: 35,
    titleKey: "simulations.tracks.caseStudy.title",
    descriptionKey: "simulations.tracks.caseStudy.description",
  },
  {
    id: "finance-quant",
    iconName: "TrendingUp",
    difficulty: "hard",
    metaCount: 8,
    metaKind: "questions",
    durationMin: 30,
    titleKey: "simulations.tracks.financeQuant.title",
    descriptionKey: "simulations.tracks.financeQuant.description",
  },
  {
    id: "pm-strategy",
    iconName: "Target",
    difficulty: "medium",
    metaCount: 5,
    metaKind: "questions",
    durationMin: 35,
    titleKey: "simulations.tracks.pmStrategy.title",
    descriptionKey: "simulations.tracks.pmStrategy.description",
  },
  {
    id: "leadership",
    iconName: "Users",
    difficulty: "adaptive",
    metaCount: 6,
    metaKind: "questions",
    durationMin: 25,
    titleKey: "simulations.tracks.leadership.title",
    descriptionKey: "simulations.tracks.leadership.description",
  },
  {
    id: "data-analytics",
    iconName: "BarChart2",
    difficulty: "medium",
    metaCount: 4,
    metaKind: "questions",
    durationMin: 30,
    titleKey: "simulations.tracks.dataAnalytics.title",
    descriptionKey: "simulations.tracks.dataAnalytics.description",
  },
  {
    id: "communication",
    iconName: "Mic2",
    difficulty: "easy",
    metaCount: 4,
    metaKind: "questions",
    durationMin: 20,
    titleKey: "simulations.tracks.communication.title",
    descriptionKey: "simulations.tracks.communication.description",
  },
] as const

export const MOCK_RECENT_SESSIONS: readonly RecentSession[] = [
  {
    id: "s1",
    role: "Senior Product Designer",
    track: "Behavioral",
    date: "Jun 14",
    durationMin: 24,
    score: 82,
    status: "completed",
  },
  {
    id: "s2",
    role: "Staff Engineer",
    track: "System Design",
    date: "Jun 11",
    durationMin: 38,
    score: 74,
    status: "completed",
  },
  {
    id: "s3",
    role: "PM, Growth",
    track: "Product Sense",
    date: "Jun 9",
    durationMin: 18,
    score: null,
    status: "in_progress",
  },
  {
    id: "s4",
    role: "Quant Analyst",
    track: "Finance · Quant",
    date: "Jun 5",
    durationMin: 12,
    score: null,
    status: "abandoned",
  },
] as const
