import type { Assessment, AssessmentDomain, AssessmentStat } from "./types"

export const ASSESSMENT_DOMAINS: readonly AssessmentDomain[] = [
  "coding",
  "caseStudy",
  "behavioral",
  "product",
  "systemDesign",
  "finance",
  "clinical",
]

export const MOCK_STATS: readonly AssessmentStat[] = [
  { id: "completed", value: 24, labelKey: "assessments.stats.completed", iconName: "CheckCircle2" },
  { id: "avgScore", value: 78, labelKey: "assessments.stats.avgScore", iconName: "Target" },
  { id: "dayStreak", value: 6, labelKey: "assessments.stats.dayStreak", iconName: "Flame" },
  { id: "hoursPracticed", value: 11, labelKey: "assessments.stats.hoursPracticed", iconName: "Timer" },
]

export const MOCK_ASSESSMENTS: readonly Assessment[] = [
  {
    id: "a1",
    title: "Two Sum — hash maps",
    domain: "coding",
    difficulty: "easy",
    durationMin: 15,
    status: "mastered",
    bestScore: 96,
    iconName: "Code2",
  },
  {
    id: "a2",
    title: "Rate a struggling SaaS product",
    domain: "caseStudy",
    difficulty: "medium",
    durationMin: 30,
    status: "inProgress",
    bestScore: null,
    iconName: "Monitor",
  },
  {
    id: "a3",
    title: "Read a chest CT for pneumonia",
    domain: "clinical",
    difficulty: "hard",
    durationMin: 20,
    status: "notStarted",
    bestScore: null,
    iconName: "Scan",
  },
  {
    id: "a4",
    title: "Design a URL shortener",
    domain: "systemDesign",
    difficulty: "hard",
    durationMin: 45,
    status: "notStarted",
    bestScore: null,
    iconName: "Network",
  },
  {
    id: "a5",
    title: "Tell me about a conflict",
    domain: "behavioral",
    difficulty: "easy",
    durationMin: 10,
    status: "mastered",
    bestScore: 88,
    iconName: "MessageSquare",
  },
  {
    id: "a6",
    title: "Merge intervals",
    domain: "coding",
    difficulty: "medium",
    durationMin: 25,
    status: "inProgress",
    bestScore: 71,
    iconName: "Code2",
  },
  {
    id: "a7",
    title: "Diagnose a 20% drop in DAU",
    domain: "product",
    difficulty: "medium",
    durationMin: 25,
    status: "notStarted",
    bestScore: null,
    iconName: "TrendingDown",
  },
  {
    id: "a8",
    title: "DCF for a SaaS company",
    domain: "finance",
    difficulty: "hard",
    durationMin: 30,
    status: "notStarted",
    bestScore: null,
    iconName: "TrendingUp",
  },
  {
    id: "a9",
    title: "Binary search variations",
    domain: "coding",
    difficulty: "medium",
    durationMin: 20,
    status: "mastered",
    bestScore: 92,
    iconName: "Code2",
  },
  {
    id: "a10",
    title: "Estimate coffee shops in NYC",
    domain: "caseStudy",
    difficulty: "easy",
    durationMin: 20,
    status: "notStarted",
    bestScore: null,
    iconName: "Monitor",
  },
  {
    id: "a11",
    title: "Prioritize next-quarter roadmap",
    domain: "product",
    difficulty: "easy",
    durationMin: 30,
    status: "inProgress",
    bestScore: 65,
    iconName: "Lightbulb",
  },
  {
    id: "a12",
    title: "Design a rate limiter",
    domain: "systemDesign",
    difficulty: "hard",
    durationMin: 40,
    status: "notStarted",
    bestScore: null,
    iconName: "Network",
  },
]
