import type { DiscoverJob, SeniorityLevel, TrackedJob, TrackingStatus } from "./types"

export const SENIORITY_FILTERS: SeniorityLevel[] = ["senior", "lead", "staff"]

export const MOCK_DISCOVER_JOBS: DiscoverJob[] = [
  {
    id: "d1",
    title: "Staff Product Designer",
    company: "Northwind",
    avatarText: "N",
    avatarColorClass: "bg-blue-600 text-white",
    isNew: true,
    location: "Remote (US)",
    remoteType: "remote",
    salaryRange: "$185K – $215K",
    seniority: "staff",
    postedAt: "2d ago",
    matchScore: 96,
    matchTier: "strong",
    fitNote: "You led a 60-component design system — exactly what this team is hiring to scale.",
    skills: [
      { label: "Design systems", matched: true },
      { label: "B2B / SaaS", matched: true },
      { label: "Product strategy", matched: true },
    ],
  },
  {
    id: "d2",
    title: "Senior Product Designer, Growth",
    company: "Acme",
    avatarText: "A",
    avatarColorClass: "bg-emerald-600 text-white",
    isNew: true,
    location: "San Francisco · Hybrid",
    remoteType: "hybrid",
    salaryRange: "$170K – $195K",
    seniority: "senior",
    postedAt: "1d ago",
    matchScore: 92,
    matchTier: "strong",
    fitNote: "Your activation-lift work maps to their growth charter; brush up on A/B tooling.",
    skills: [
      { label: "Prototyping", matched: true },
      { label: "User research", matched: true },
      { label: "Data viz", matched: true },
      { label: "Experimentation", matched: false },
    ],
  },
  {
    id: "d3",
    title: "Design Lead, Platform",
    company: "Globex",
    avatarText: "G",
    avatarColorClass: "bg-emerald-700 text-white",
    isNew: false,
    location: "New York · Hybrid",
    remoteType: "hybrid",
    salaryRange: "$190K – $220K",
    seniority: "lead",
    postedAt: "4d ago",
    matchScore: 88,
    matchTier: "good",
    fitNote: "Strong systems overlap; the role adds direct reports beyond your current scope.",
    skills: [
      { label: "Design systems", matched: true },
      { label: "Team leadership", matched: true },
      { label: "Cross-platform", matched: true },
    ],
  },
]

export const TRACKING_STATUS_ORDER: TrackingStatus[] = ["saved", "applied", "interviewing", "offer"]

export const TRACKING_STATUS_TRENDS: Record<TrackingStatus, number> = {
  saved: 12,
  applied: 18,
  interviewing: -5,
  offer: 50,
}

export const MOCK_TRACKED_JOBS: TrackedJob[] = [
  {
    id: "t1",
    title: "Sr. UX Designer",
    company: "Hooli",
    location: "Remote",
    avatarText: "H",
    avatarColorClass: "bg-amber-600 text-white",
    status: "interviewing",
    nextStep: "Onsite loop — Thu 2pm",
    nextStepDate: "in 2 days",
    matchScore: 86,
    progressSteps: 4,
    progressCompleted: 2,
    activeStepIndex: 2,
    statusUpdatedAt: "Applied 8d ago",
  },
  {
    id: "t2",
    title: "Design Manager",
    company: "Massive",
    location: "Boston · Hybrid",
    avatarText: "M",
    avatarColorClass: "bg-neutral-700 text-white",
    status: "interviewing",
    nextStep: "Portfolio review — prep deck",
    nextStepDate: "tomorrow",
    matchScore: 83,
    progressSteps: 4,
    progressCompleted: 2,
    activeStepIndex: 2,
    statusUpdatedAt: "Applied 11d ago",
  },
  {
    id: "t3",
    title: "Product Designer",
    company: "Initech",
    location: "Austin",
    avatarText: "I",
    avatarColorClass: "bg-violet-600 text-white",
    status: "applied",
    nextStep: "Follow up with recruiter",
    nextStepDate: "in 4 days",
    matchScore: 79,
    progressSteps: 4,
    progressCompleted: 1,
    activeStepIndex: 1,
    statusUpdatedAt: "Applied 5d ago",
  },
  {
    id: "t4",
    title: "Lead Product Designer",
    company: "Soylent",
    location: "Remote (US)",
    avatarText: "S",
    avatarColorClass: "bg-emerald-600 text-white",
    status: "saved",
    nextStep: "Tailor resume & apply",
    nextStepDate: "no date",
    matchScore: 74,
    progressSteps: 4,
    progressCompleted: 0,
    activeStepIndex: null,
    statusUpdatedAt: "Saved just now",
  },
]
