import type { ResumeItem } from "./types"

export const MOCK_RESUMES: ResumeItem[] = [
  {
    id: "1",
    title: "Master resume",
    targetRole: null,
    company: null,
    atsScore: null,
    status: "active",
    updatedAt: "Edited yesterday",
    avatarText: "DR",
  },
  {
    id: "2",
    title: "Senior Product Designer",
    targetRole: "Senior Product Designer",
    company: "Acme Corp",
    atsScore: 84,
    status: "active",
    updatedAt: "Edited 2 days ago",
    avatarText: "A",
  },
  {
    id: "3",
    title: "Product Designer",
    targetRole: "Product Designer",
    company: "Linear",
    atsScore: 78,
    status: "draft",
    updatedAt: "Edited 5 days ago",
    avatarText: "L",
  },
  {
    id: "4",
    title: "Design Lead",
    targetRole: "Design Lead",
    company: "Northwind",
    atsScore: 91,
    status: "active",
    updatedAt: "Edited 1 week ago",
    avatarText: "N",
  },
  {
    id: "5",
    title: "UX Designer",
    targetRole: "UX Designer",
    company: "Globex",
    atsScore: 66,
    status: "draft",
    updatedAt: "Edited 2 weeks ago",
    avatarText: "G",
  },
  {
    id: "6",
    title: "Staff Product Designer",
    targetRole: "Staff Product Designer",
    company: "Vercel",
    atsScore: 88,
    status: "archived",
    updatedAt: "Edited 1 month ago",
    avatarText: "V",
  },
]
