import type { ResumeItem, ResumeTemplate, ResumeTemplateCategory } from "./types"

export const MOCK_RESUMES: ResumeItem[] = [
  {
    id: "1",
    title: "Master resume",
    targetRole: null,
    company: null,
    atsScore: null,
    status: "active",
    updatedAt: "Edited yesterday",
    avatarText: "DR",
  },
  {
    id: "2",
    title: "Senior Product Designer",
    targetRole: "Senior Product Designer",
    company: "Acme Corp",
    atsScore: 84,
    status: "active",
    updatedAt: "Edited 2 days ago",
    avatarText: "A",
  },
  {
    id: "3",
    title: "Product Designer",
    targetRole: "Product Designer",
    company: "Linear",
    atsScore: 78,
    status: "draft",
    updatedAt: "Edited 5 days ago",
    avatarText: "L",
  },
  {
    id: "4",
    title: "Design Lead",
    targetRole: "Design Lead",
    company: "Northwind",
    atsScore: 91,
    status: "active",
    updatedAt: "Edited 1 week ago",
    avatarText: "N",
  },
  {
    id: "5",
    title: "UX Designer",
    targetRole: "UX Designer",
    company: "Globex",
    atsScore: 66,
    status: "draft",
    updatedAt: "Edited 2 weeks ago",
    avatarText: "G",
  },
  {
    id: "6",
    title: "Staff Product Designer",
    targetRole: "Staff Product Designer",
    company: "Vercel",
    atsScore: 88,
    status: "archived",
    updatedAt: "Edited 1 month ago",
    avatarText: "V",
  },
]

export const TEMPLATE_CATEGORIES: ResumeTemplateCategory[] = [
  "tech",
  "healthcare",
  "finance",
  "consulting",
  "engineering",
  "legal",
]

export const MOCK_TEMPLATES: ResumeTemplate[] = [
  {
    id: "t1",
    title: "Software Engineer",
    company: "Microsoft",
    category: "tech",
    description: "Big-tech engineering format",
    avatarText: "MS",
  },
  {
    id: "t2",
    title: "Investment Banking Analyst",
    company: "Goldman Sachs",
    category: "finance",
    description: "Deal-sheet structure",
    avatarText: "GS",
  },
  {
    id: "t3",
    title: "Cardiologist",
    company: "Sheba — Tel HaShomer",
    category: "healthcare",
    description: "Clinical CV with publications",
    avatarText: "S",
  },
  {
    id: "t4",
    title: "Management Consultant",
    company: "McKinsey & Company",
    category: "consulting",
    description: "Case-driven impact format",
    avatarText: "MC",
  },
  {
    id: "t5",
    title: "Mechanical Engineer",
    company: "Tesla",
    category: "engineering",
    description: "Hardware project showcase",
    avatarText: "T",
  },
  {
    id: "t6",
    title: "Corporate Associate",
    company: "Skadden",
    category: "legal",
    description: "Practice-area focused CV",
    avatarText: "SK",
  },
  {
    id: "t7",
    title: "Frontend Engineer",
    company: "Vercel",
    category: "tech",
    description: "Startup product format",
    avatarText: "V",
  },
  {
    id: "t8",
    title: "Registered Nurse",
    company: "Mayo Clinic",
    category: "healthcare",
    description: "Patient-care experience format",
    avatarText: "MC",
  },
]
